// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/inventory/inventory.proto

package mu_micro_book_srv_inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Inventory service

type InventoryService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Inventory_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Inventory_PingPongService, error)
}

type inventoryService struct {
	c    client.Client
	name string
}

func NewInventoryService(name string, c client.Client) InventoryService {
	return &inventoryService{
		c:    c,
		name: name,
	}
}

func (c *inventoryService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Inventory.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Inventory_StreamService, error) {
	req := c.c.NewRequest(c.name, "Inventory.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &inventoryServiceStream{stream}, nil
}

type Inventory_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type inventoryServiceStream struct {
	stream client.Stream
}

func (x *inventoryServiceStream) Close() error {
	return x.stream.Close()
}

func (x *inventoryServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *inventoryServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *inventoryServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *inventoryServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *inventoryService) PingPong(ctx context.Context, opts ...client.CallOption) (Inventory_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Inventory.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &inventoryServicePingPong{stream}, nil
}

type Inventory_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type inventoryServicePingPong struct {
	stream client.Stream
}

func (x *inventoryServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *inventoryServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *inventoryServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *inventoryServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *inventoryServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *inventoryServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Inventory service

type InventoryHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Inventory_StreamStream) error
	PingPong(context.Context, Inventory_PingPongStream) error
}

func RegisterInventoryHandler(s server.Server, hdlr InventoryHandler, opts ...server.HandlerOption) error {
	type inventory interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Inventory struct {
		inventory
	}
	h := &inventoryHandler{hdlr}
	return s.Handle(s.NewHandler(&Inventory{h}, opts...))
}

type inventoryHandler struct {
	InventoryHandler
}

func (h *inventoryHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.InventoryHandler.Call(ctx, in, out)
}

func (h *inventoryHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.InventoryHandler.Stream(ctx, m, &inventoryStreamStream{stream})
}

type Inventory_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type inventoryStreamStream struct {
	stream server.Stream
}

func (x *inventoryStreamStream) Close() error {
	return x.stream.Close()
}

func (x *inventoryStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *inventoryStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *inventoryStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *inventoryStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *inventoryHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.InventoryHandler.PingPong(ctx, &inventoryPingPongStream{stream})
}

type Inventory_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type inventoryPingPongStream struct {
	stream server.Stream
}

func (x *inventoryPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *inventoryPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *inventoryPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *inventoryPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *inventoryPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *inventoryPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
